trigger:
  branches:
    include:
      - main

variables:
  - group: aws-credentials

pool:
  name: self-hosted

stages:
  - stage: Terraform_Apply
    jobs:
      - job: Terraform
        steps:
          - checkout: self

          - script: |
              sudo apt-get update
              sudo apt-get install -y unzip curl
              curl -O https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
              unzip terraform_1.8.3_linux_amd64.zip
              sudo mv terraform /usr/local/bin/
            displayName: 'Install Terraform'

          - script: |
              export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
              export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
              export AWS_REGION=$(AWS_REGION)

              terraform init
              terraform validate
              terraform plan -var-file="terraform.tfvars"
              terraform apply -auto-approve -var-file="terraform.tfvars"
            displayName: 'Run Terraform'
