trigger:
  branches:
    include:
      - main

variables:
  - group: aws-credentials

pool:
  name: self-hosted 
stages:
  - stage: Terraform_Apply
    jobs:
      - job: Terraform
        steps:
          - checkout: self

          - powershell: |
              Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_windows_amd64.zip" -OutFile terraform.zip
              Expand-Archive -Path terraform.zip -DestinationPath .
              Move-Item .\terraform.exe "C:\Windows\System32\" -Force
            displayName: 'Install Terraform (Windows)'

          - powershell: |
              $env:AWS_ACCESS_KEY_ID = "$(AWS_ACCESS_KEY_ID)"
              $env:AWS_SECRET_ACCESS_KEY = "$(AWS_SECRET_ACCESS_KEY)"
              $env:AWS_REGION = "$(AWS_REGION)"

              terraform version
              terraform init
              terraform validate
              terraform plan -var-file="terraform.tfvars"
              terraform apply -auto-approve -var-file="terraform.tfvars"
            displayName: 'Run Terraform'
