trigger:
  branches:
    include:
      - main

variables:
  - group: aws-credentials

pool:
  name: self-hosted

stages:
  - stage: Terraform_Apply
    jobs:
      - job: Terraform
        steps:
          - checkout: self

          - powershell: |
              Invoke-WebRequest -Uri https://releases.hashicorp.com/
